### ISSUE TITLE
[bug] time calculation in discord RPC incorrect

### ISSUE THREAD

**Issue by xCykrix** [BigBrainAFK/YouTube-Music-Client#2]
Hey there, I've tried taking a look but I haven't had enough time to research your means of time calculation that you are using. I believe this started occurring after the update to enable the additional windows features.

I've noticed it loves to hover around 5 hours of playtime and jump around as the song plays, I believe that may be an upper bound for the RPC service.

Reference: 
![0de56e04e0-8a3c-9dd3](https://user-images.githubusercontent.com/12182390/70858983-b6144000-1ed1-11ea-9361-9f80b3a2d59b.gif)

Reproduction:
It should be as simple as playing a song and watching the RPC.

YouTube Music Client Version: `v1.1.1 Release`
OS: `Windows 7 - Ultimate`
Discord: `[BUILD INFO] Release Channel: PTB, Build Number: 51458`

**Comment by xCykrix** [comment]
Right near the end of the above gif, the time jumps from near the 5 hours mark to around 3 hours.

**Comment by BigBrainAFK** [comment]
This should be fixed in the new release
